### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by billimek** [homedepot/spingo#3]
**Is your feature request related to a problem? Please describe.**
This repo should have automated CI for commits.  As it is mostly terraform-based, a `terraform validate` should be part of the automation

**Describe the solution you'd like**
Create a script that will:

* temporarily create necessary `.auto.tfvars` files in each of the terraform top-level directories (certbot, dns, halyard. spinnaker)
* temporarily create necessary `override.tf` files in each of the terraform top-level directories (certbot, dns, halyard. spinnaker)
* for each of the terraform directories, run `terraform init` followed by `terraform validate`

**Comment by billimek** [comment]
We will work on this once the terraform vault provider is updated to work with terraform 0.12.  See [#424](https://github.com/terraform-providers/terraform-provider-vault/issues/424) for more detail.

**Comment by billimek** [comment]
We should also add a script linter for the stuff in the `scripts` directory.  For example, with CircleCI something like this in the `.circleci/config.yml` file:

```yaml
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: shellcheck -x scripts/*.sh
```
